// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartJsController from "./chart_js_controller"
application.register("chart-js", ChartJsController)

import ChartpageController from "./chartpage_controller"
application.register("chartpage", ChartpageController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import QuestCounterController from "./quest_counter_controller"
application.register("quest-counter", QuestCounterController)

import TestController from "./test_controller"
application.register("test", TestController)
