meta_name: "Quest Buddy"
meta_title: "Quest Buddy - Become the best buddy"
meta_description: "Come here if you want to improve yours skills with fun"
meta_image: "cover.png" # should exist in `app/assets/images/`
